version: 0.2

env:
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo ${default-region}

artifacts:
  files:
    - api_imagedefinitions.json
    - front_imagedefinitions.json