version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
    - REPO_API=$(aws ecr describe-repositories --repository-names api --output text --query "repositories[0].repositoryUri")
    - IMAGE_API=$REPO_API:latest
    - REPO_FRONT=$(aws ecr describe-repositories --repository-names front --output text --query "repositories[0].repositoryUri")
    - IMAGE_FRONT=$REPO_FRONT:latest
  build:
    commands:
    - cd api
    - docker build -t $IMAGE_API .
    - docker push $IMAGE_API
    - cd ..
    - cd front
    - docker build -t $IMAGE_FRONT .
    - docker push $IMAGE_FRONT
  post_build:
    commands:
    - printf '[{"name":"api","imageUri":"%s"}]' $IMAGE > api_imagedefinitions.json
    - printf '[{"name":"front","imageUri":"%s"}]' $IMAGE > front_imagedefinitions.json
artifacts:
  files:
    - api_imagedefinitions.json
    - front_imagedefinitions.json