version: 0.2

env:
  parameter-store:
    AWS_DEFAULT_REGION: default-region
    AWS_ACCOUNT_ID: account-id
    API_IMAGE: api-image
    API_IMAGE_TAG: api-image-tag
    FRONT_IMAGE: front-image
    FRONT_IMAGETAG: front-image-tag
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - docker build -t $API_IMAGE ./api
      - docker push $API_IMAGE
      - docker build -t $FRONT_IMAGE ./front
      - docker push $FRONT_IMAGE
  post_build:
    commands:
      - printf '[{"name":"api","imageUri":"%s"}]' $API_IMAGE > api_imagedefinitions.json
      - printf '[{"name":"front","imageUri":"%s"}]' $FRONT_IMAGE > front_imagedefinitions.json
artifacts:
  files:
    - api_imagedefinitions.json
    - front_imagedefinitions.json